"""add last_accessed_at

Revision ID: 3d06256a1b9d
Revises: 9e0a78c33af3
Create Date: 2026-08-11 23:39:36.381794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d06256a1b9d'
down_revision: Union[str, Sequence[str], None] = '9e0a78c33af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_items', sa.Column('last_accessed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_items', 'last_accessed_at')
    # ### end Alembic commands ###
