"""add embedding column

Revision ID: cdedcba7746d
Revises: 3d06256a1b9d
Create Date: 2026-08-30 15:00:41.461321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdedcba7746d'
down_revision: Union[str, Sequence[str], None] = '3d06256a1b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_items', sa.Column('embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_items', 'embedding')
    # ### end Alembic commands ###
